# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          yasink.at - personal blog
paginate:       5
baseurl:        ""
url:            "http://yasink.at"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Yasin Kavakli
  url:          http://yasink.at
  email:        hello@yasink.at

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
